In [1]:
import mysql.connector
import pandas as pd

import bt4301

bt4301.set_default_pandas_options(max_columns=50, max_colwidth=100)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [2]:
db_datawarehouse = mysql.connector.connect(
	host='localhost',
	user='bt4301',
	passwd='password',
	database='datawarehouse'
)

In [3]:
# retrieve sales

str_sql = '''
SELECT *
FROM sales
ORDER BY sales.SalesOrderID, sales.SalesOrderDetailID ASC
'''
df = pd.read_sql(sql=str_sql, con=db_datawarehouse)
df = df[:10]
df

/tmp/ipykernel_15380/1761360801.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql=str_sql, con=db_datawarehouse)

   index  SalesOrderID  SalesOrderDetailID  ProductID  OrderQty  UnitPrice  UnitPriceDiscount  LineTotal  CustomerID
0      0         43697                 353        749         1    3578.27               0.00    3578.27       21768
1      1         43698                 354        773         1    3399.99               0.00    3399.99       28389
2      2         43699                 355        773         1    3399.99               0.00    3399.99       25863
3      3         43700                 356        767         1     699.10               0.00     699.10       14501
4      4         43701                 357        773         1    3399.99               0.00    3399.99       11003
5      5         43702                 358        750         1    3578.27               0.00    3578.27       27645
6      6         43703                 359        749         1    3578.27               0.00    3578.27       16624
7      7         43704                 360        778         1    3374.99               0.00    3374.99       11005
8      8         43705                 361        771         1    3399.99               0.00    3399.99       11011
9      9         43706                 362        751         1    3578.27               0.00    3578.27       27621

In [4]:
df_fp = bt4301.add_fingerprint_column(df)
df_fp

   index  SalesOrderID  SalesOrderDetailID  ProductID  OrderQty  UnitPrice  UnitPriceDiscount  LineTotal  CustomerID                                                               _fp
0      0         43697                 353        749         1    3578.27               0.00    3578.27       21768  4c094e50eee685d06280baa8b3dbfdc8a1c767dade8dca801bb8a344d5eb93af
1      1         43698                 354        773         1    3399.99               0.00    3399.99       28389  5cc8d91c75580f428a5462c2ad015aa8eb67c91ac2c55c5c72fbae1fb9207cc9
2      2         43699                 355        773         1    3399.99               0.00    3399.99       25863  7455d3826145a4658ebbebdc09767850daa0f592fc3c79c6d757d74ffa02fd34
3      3         43700                 356        767         1     699.10               0.00     699.10       14501  7b85525f135e3d1a8a69505a5a8c8e5d5f86b3a81d61c932639a4b490d6eed18
4      4         43701                 357        773         1    3399.99               0.00    3399.99       11003  cb6f05881d16d839abb148022594a76be1c4b4ab52619cf907c69194f31d57c7
5      5         43702                 358        750         1    3578.27               0.00    3578.27       27645  bfaf169f4cd9acfb1253174bdc04b78c2904d765c979cf57244d24336ab44ed6
6      6         43703                 359        749         1    3578.27               0.00    3578.27       16624  854bc6c34b6d0ec7265d26802609505fa2ab6441cc643278a19ae465b51af3b4
7      7         43704                 360        778         1    3374.99               0.00    3374.99       11005  8a4fa10f9a71d66dddbd0e43c5765a45d3b0417ed9f904f92a5a99857d8d41ed
8      8         43705                 361        771         1    3399.99               0.00    3399.99       11011  71918f82f44d3a76918fc3fc744416598cac443aeaaad07e8cb58d7eec0e92b8
9      9         43706                 362        751         1    3578.27               0.00    3578.27       27621  8f80d81438cf8ac21f3b28a0c30331614bca177beb6e51dc95f5cd71a222d9f0

In [5]:
# Simulate data change by changing OrderQty
df['OrderQty'] = df['OrderQty'] + 1

df_fp = bt4301.add_fingerprint_column(df)
df_fp

   index  SalesOrderID  SalesOrderDetailID  ProductID  OrderQty  UnitPrice  UnitPriceDiscount  LineTotal  CustomerID                                                               _fp
0      0         43697                 353        749         2    3578.27               0.00    3578.27       21768  fe8ddce0ff7b515ce33534144413649cbc8ec2a7f55c0e9d642cef955510f358
1      1         43698                 354        773         2    3399.99               0.00    3399.99       28389  ee712802d81ceeccbe60774a7f8b524d2f9a7763676865d04bd9bdc9863c9299
2      2         43699                 355        773         2    3399.99               0.00    3399.99       25863  37c0473b4f64eb00dfe25673102397ae9b7e4dc7b59530b6923a11a3ea6049be
3      3         43700                 356        767         2     699.10               0.00     699.10       14501  7a1c9e9326cebe31a770e2627d9cededf8c084f9a340b3eafe008a775b7aecf3
4      4         43701                 357        773         2    3399.99               0.00    3399.99       11003  6abab60d995c93a8561c0ed6076b65211172f3264aeba19d59b945b2391bedc0
5      5         43702                 358        750         2    3578.27               0.00    3578.27       27645  8cee6f20806b6e8b7720e18fa879d01b2a79b5c5b1746c8f3105596a362066e3
6      6         43703                 359        749         2    3578.27               0.00    3578.27       16624  bca1d9fe9e0ff9be4ff9536fd56ab419a047b157e231bea80dc3ebbfa2b8fb9a
7      7         43704                 360        778         2    3374.99               0.00    3374.99       11005  afae2f09d1ebcebff915aa21f79c1242c0cc6bc2619c6a4755689445bd501efd
8      8         43705                 361        771         2    3399.99               0.00    3399.99       11011  f9ddbbf7160c7c4e0d00aeb9565f7b3b0f65b930a376e8702077925cab61dc88
9      9         43706                 362        751         2    3578.27               0.00    3578.27       27621  c9d5128cf6b7dd3f1cda80c103d784eec5be94b3ad2e7f55c4f373a2e633f1b6